### ISSUE TITLE
When creating a framework, a user can not define a subject

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#1573] opened 2021-09-21 20:30 UTC
When creating an Item a user can define a item type, but when creating a document a user can not create a subject. >they shoudl be a way to create a subject in the system without being an admin. The process for item type should apply to subject.

**Comment by roverwolf** [comment] 2021-09-24 22:44
Duplicate of #194

**Closed by roverwolf** 2021-09-24 22:44 UTC
Labels: Type - Enhancement, Severity 3 - Essential
