### ISSUE TITLE
hanging cursor

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#149] opened 2017-09-21 18:28 UTC
When items from a framework are copied and pointing at the item being copied, the tooltip stays.

**Comment by brandonopened** [comment] 2017-09-21 18:29
<img width="1118" alt="screen shot 2017-09-20 at 3 01 04 pm" src="https://user-images.githubusercontent.com/14943151/30712193-0b92f9fc-9ec0-11e7-998f-22ed6ea3265b.png">

**Comment by brandonopened** [comment] 2017-09-21 18:29
![image uploaded from ios](https://user-images.githubusercontent.com/14943151/30712217-1ee5a108-9ec0-11e7-9ddb-f4c384209d5a.jpg)

**Comment by roverwolf** [comment] 2017-10-04 17:33
This is now causing significant issues for Greg during demos.

**Comment by roverwolf** [comment] 2017-10-05 18:34
Joshua thinks this may be related to #116 (as that is when this occurs, at least most readily).

**Comment by Vishvesh-LM** [comment] 2017-10-05 19:36
Nilesh - my JavaScript guy couldn't replicate this on Chrome. I will get him to look at #116 as well. 

In the meantime, which browsers we have seen this on?

**Comment by NileshPatreLM** [comment] 2017-10-11 14:00
I have tried to copy items from one framework to another framework but , I wan not able to reproduce this issue. I have attached a video.
Is this the correct way to copy items to reproduce the issue or there is some other way

[2017-10-11_14h50_55.zip](https://github.com/opensalt/opensalt/files/1375832/2017-10-11_14h50_55.zip)

**Comment by peppersc** [comment] 2017-10-11 19:37
I've checked in a fix for this issue in the peppersc6 branch.

**Closed** 2017-10-11 23:52 UTC
Labels: Priority 1 - High, Severity 2 - Urgent, Type - Bug
